### ISSUE TITLE
CT selection 검색창에 enter 로 검색 가능하도록

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#1]
CT selection 상태에서 대상 검색을 위해 검색창에 입력을 한후 enter 로 검색할 수 없고 반드시 search 버튼을 눌러아먄 동작합니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.
검색창에 검색어를 친경우(활성화 되어 있는 상태) Enter 검색

**Comment by Dalaway** [comment]
![캡처](https://user-images.githubusercontent.com/67160138/97556522-f5317e00-1a1c-11eb-86b6-d678fce3ec83.PNG)
Enter Issue 수정 확인하였습니다
