### ISSUE TITLE
Segmentation - panel 에 wheel 에 반응하지 않는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#10]
Segmentation view 에서 각종 상황에 따라 왼쪽 panel 의 scroll 이 마우스 wheel 로 조작되지 않는 경우들이 많습니다.
커서가 panel 위에 올려져있다면 항상 wheel 로 scroll 되어야 합니다.

현재, 최초 segmentation 상태 및 마우스가 각종 control 들에 걸려있을 때 wheel 을 동작하면 scroll 되지 않고, 이후 다른 위치에서도 wheel 로 scroll 할 수 없습니다. 

![image](https://user-images.githubusercontent.com/49409100/93847388-be5f9e00-fce1-11ea-8d78-3a3c6ef033ef.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
Panel Mouse Wheel Issue 수정 확인하였습니다.
