### ISSUE TITLE
각 선택된 tool 에 따라 message view 내용 변경

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#12]
현재 선택된 tool(icon button)에 따라 해당 기능이나 사용법을 설명하는 메시지가 Message view 에 표시 되어야 합니다.

이 메시지는 별도의 파일에 저장되어있는 text를 사용하도록 하면 좋겠습니다. 

![image](https://user-images.githubusercontent.com/49409100/93847788-e4d20900-fce2-11ea-9d12-392aa4945479.png)

**Comment by jhpark-rs** [comment]
해당 기능에 대한 설명문을 작성해주시면 반영하겠습니다.
가급적, 설명문을 짧게 작성하여 메시지 창에 넘치지 않아야 합니다.

**Comment by alkee-skia** [comment]
> 해당 기능에 대한 설명문을 작성해주시면 반영하겠습니다.

본문에 작성했듯이, 별도의 파일에 저장되어있는 text를 사용해주시면 좋을 것 같습니다.

예)
```ini
; INI style example

[en-US]
; 아무 tool 도 선택되어있지 않거나, text 항목을 찾을 수 없는 경우 설정되어있지 않은 경우 default 사용
default = Select one tool in the panel to segment target(s).
view.pan = Hold mouse left button and drag on the image to move over.
view.zoom = 
view.wwl = 
view.rotate = 
view.slice = 
view.rotate = 
view.reset = 
segmentation.brush = 
segmentation.eraser =
segmentation.pen =
segmentation.wand =
segmentation.grow-shrink =
```

이와같은 형식이 괜찮으시면, message 내용은 채워서 보내드리도록 하겠습니다.

**Comment by DPseol** [comment]
버튼 누를때 내타내고 싶은 메세지를 예시 처럼 주시면 적용 하도록 하겠습니다.
현재는 2줄 의 공간을 두고있습니다. 최대한 간략히 주시면 감사하겠습니다.

**Comment by alkee-skia** [comment]
@DPseol sample ini 파일을 아래와같이 제안드립니다.  보내주시는 작동버전을 확인하고 내용은 수정해 다시 공유드리도록 하겠습니다.

```ini
; UTF-8 encoding

; 별도 locale 선택되어있지 않을 경우(기본값;en-US)
[default]
; 아무 tool 도 선택되어있지 않은 상황 또는 항목(key)을 찾을 수 없는 경우 default 사용
default = Select one in the tool panel.

view.pan = Hold mouse left button and drag to move parallel to the current view plane.
; 추후 내용은 보내주신 프로그램에 직접 파일을 적용해 테스트해보고자 합니다.
; 영역 및 텍스트 정보량 확인을 위한 임시 값
view.zoom = 1234567890_2345678901_3456789012_4567890123_5678901234_6789012345_7890123456_8901234567_90
view.wwl = iiiiiiiii_iiiiiiiii_iiiiiiiii_iiiiiiiii_iiiiiiiii_iiiiiiiii_iiiiiiiii_iiiiiiiii_iiiiiiiii_
view.rotate = WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_WWWWWWWWW_
view.slice = ooooooooo_ooooooooo_ooooooooo_ooooooooo_ooooooooo_ooooooooo_ooooooooo_ooooooooo_ooooooooo_

; reset 등 선택 없이 한번의 클릭으로 명령이 실행되는 경우는 별도의 message 를 표시할 수 없습니다.

segmentation.brush = Drag to fill the area.
segmentation.eraser = Drag to reset(clear) the area.
segmentation.pen = Select lesion area to segmentation by live-wire.
segmentation.wand = Point to select lesion area by clicking.
segmentation.grow-shrink = Make grow or shirink the selected lesion.

tool.ruler = Measure a length of two points in 2D slice image.
tool.protractor = Measure a angle in 2D slice image.
tool.historgram = Show the intensity histogram in a section of 2D slice image.


; 추후 locale 지원을 위한 예시(참고용). 여기게 포함되어있지 않은 key 는 [default] 를 따르도록
[ko-KR]
default = 도구 패널에서 사용할 도구를 선택해주세요.
```

**Comment by DPseol** [comment]
Mars 에서 외부 언어파일 읽어오는 파일은 Mars 실행파일 아래 폴더 Languages 에서 읽어오고 있습니다.
Languages 폴더에 한글일경우 Lng_kor.lng 영어 일경우 Lng_eng.lng 파일로 상황에 맞게 읽어오고 있습니다.

위에 써주신 ToolMessage에 들어갈 메세지는 Lng_kor.lng, Lng_eng.lng 에 써주신 메세지와 동일하게
아래와 같이 추가될 예정입니다.

;-----------------------------------------------
;ToolMessage
IDS_MSG_SEGMENTATION_BRUSH=Drag to fill the area
IDS_MSG_SEGMENTATION_ERASE=Drag to reset(clear) the area
IDS_MSG_SEGMENTATION_PEN=Select lesion area to segmentation by live-wire
IDS_MSG_SEGMENTATION_WAND=Point to select lesion area by clicking
IDS_MSG_SEGMENTATION_G_S=Make grow or shirink the selected lesion
IDS_MSG_TOOL_RULER=Measure a length of two points in 2D slice image
IDS_MSG_TOOL_PROTRACTOR=Measure a angle in 2D slice image
IDS_MSG_TOOL_HISTROGRAM= Show the intensity histogram in a section of 2D slice image

IDS_ 로 시작되는 부분은 Mars 내부에서 대문자로 통일되고 공통으로 사용되며 내부에서 언어파일 읽어올때 참고하여 읽어오고 있습니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![Message View 모음](https://user-images.githubusercontent.com/67160138/97377007-4bf66500-1902-11eb-9a4e-3d108d522776.png)
Message View 확인하였습니다.
