### ISSUE TITLE
각종 size 에 단위 표시

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#13]
segmentation 의 각 툴설정에 나타나있는 입력값에 size 가 있는경우 단위(pixel, mm, cm 등)가 함께 표시되어야 합니다.

![image](https://user-images.githubusercontent.com/49409100/93848067-abe66400-fce3-11ea-9da7-69a5e533746c.png)

**Comment by alkee-skia** [comment]
brush, eraser 의 size 값 옆에 mm 표시되어야하고, wand 의 radius 에도 mm 표시가 필요합니다.

wand 의 range 의 경우 사용 단위 확인후 알맞은 단위 표시가 필요합니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![1](https://user-images.githubusercontent.com/67160138/96963152-1e489f00-1543-11eb-8081-55fa9b6bc9d8.PNG)
![2](https://user-images.githubusercontent.com/67160138/96963153-1e489f00-1543-11eb-88fd-89e4f479c8e9.PNG)
![3](https://user-images.githubusercontent.com/67160138/96963151-1d177200-1543-11eb-9901-963f8fc80ec8.PNG)

Brush, Eraser, Wand 사이즈 반영 확인하였습니다.
