### ISSUE TITLE
작업 영역(axial view)이 tool 위치와 근접하도록

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#14]
segmentation 의 주 영역인 Axial 이 panel 과 멀리 떨어져있어 불편합니다. VR 과 Axial 의 기본 위치를 변경하면 좋겠습니다.

![image](https://user-images.githubusercontent.com/49409100/93848645-29f73a80-fce5-11ea-81ce-941b3e2834f7.png)

**Comment by jhpark-rs** [comment]
수정 완료

**Comment by alkee-skia** [comment]
[MARS_v1940](https://github.com/alkee-skia/mars-processor/milestone/4)에서 수정내용 확인했습니다
