### ISSUE TITLE
Imgs (image count) 수가 맞지 않음

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#15]
CT selection 의 study-series 목록에 Imgs(DICOM image count) 숫자가 맞지 않습니다.

![image](https://user-images.githubusercontent.com/49409100/93848723-6034ba00-fce5-11ea-92fb-c612baea677f.png)

**Comment by alkee-skia** [comment]
[MARS1016](https://github.com/alkee-skia/mars-processor/milestone/3) 에서 수정내용을 확인하였으나, study 항목에서는 imgs 가 seires 개수를 나타내는 듯 합니다. 

이와같이 표헌하는 경유 xelis 와 같은 방식이 조금 더 나을 것 같습니다. xelis 에서는 `imgs` column 이 study 항목에서는 다음과 같이 표기되고있습니다.  전체이미지수( series 수)

 | xelis 예 | MARS1016 |
|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/96359911-e1e7fe00-1152-11eb-86cc-87295da3d465.png) | ![image](https://user-images.githubusercontent.com/49409100/96359923-ed3b2980-1152-11eb-9e7d-7946bcbf4d98.png) |

**Comment by DPseol** [comment]
MARS 1016 버전에서 수정. 현재 Study는 Series 개수 만 표현.
추후  Image 전체 카운트+Series 개수 수정 예정.

**Comment by alkee-skia** [comment]
@DPseol 
> 추후 Image 전체 카운트+Series 개수 수정 예정.

수정내용 확인하면 issue close 하도록 하겠습니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![series](https://user-images.githubusercontent.com/67160138/96964619-bfd0f000-1545-11eb-8e12-da16a13eae7e.png)
Image 전체 개수 + Series 개수 수정 확인하였습니다.
