### ISSUE TITLE
잘못된 방향으로 DICOM image 표시

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#16]
선택한 CT series 가 original axial 이 아닐 경우 segmentation view 에 올바르지 않은 방향의 데이터가 보여집니다.

[`patientPosition`](https://dicom.innolitics.com/ciods/ct-image/general-series/00185100) / `imageOrientationPatient` 에 따라 [알맞게 표시](https://nipy.org/nibabel/dicom/dicom_orientation.html#dicom-z-from-slice)하거나, 지원하지 않는 series 의 경우 데이터 선택이 불가능하도록 되어야 할 것.

 * 지원하지 않는 series 의 경우, 애초에 표시(리스팅)하지 않는 방법 ; 사용자에게 비직관적인 부분이 있으나, 가장 간단히 해볼 수 있을 것으로 보여짐
 * image orientation 이외에 image count(bounding box, slice thickness size) 제약, modality 제약(CT only) 등이 필요할 것.

| CT selection | Segmentation  |
|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/93849762-bf93c980-fce7-11ea-8f25-5c27df15145b.png) | ![image](https://user-images.githubusercontent.com/49409100/93849771-c3275080-fce7-11ea-8ada-2efd3e1d8306.png) |

**Comment by DPseol** [comment]
MARS 1016 버전에서 수정.

**Comment by jhpark-rs** [comment]
image orientation(0x0020, 0x0037) 참조하여 방향 수정 중입니다.
이 부분은 좀 더 시간이 필요할 것 같습니다.

**Comment by jhpark-rs** [comment]
10/26 논의 결과에 따라 axial reconstruction 방법으로 해결 하였습니다.

**Comment by alkee-skia** [comment]
v1956 에서 수정된 것을 확인했습니다.
