### ISSUE TITLE
status 표시 적용

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#17]
status 는 `/v2/Mars/WorkList` 의 response(return) 안에 `StatusMessage` 로 넣었습니다. 이를 CT selection  - series list 의 status column 에 출력해주세요. 또한, Segmentation 에 진입하면(올바르게 데이터를 로드했으면) `/v2/Mars/ReviewStatus/{dicomSeriesId}` web-api ([PATCH method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) 임을 주의)를 호출해주세요. 
![image](https://user-images.githubusercontent.com/49409100/93858739-9d09ac80-fcf7-11ea-8076-b0c6d39b5257.png)

자세한 내용은 [mars api 문서](http://my.alkee.net:40088/swagger/index.html)를 참고해주세요.

(참고) `/v2/Mars/WorkList` API 의 response(return) 구조 (c#)

```csharp
        /// <summary>
        /// Dicom prosessor 에서 사용할 study-series 묶음. (query 에 대한 응답)
        /// </summary>
        public class WorkItem
        {
            public class Subitem
            {
                public db.DicomSeries DicomSeries { get; set; }
                public db.ArStudy ArStudy { get; set; }
                public db.UserData UserData { get; set; }
                public string StatusMessage { get; set; } // 임시. #460 ; 클라이언트의 status 표시 logic 부담을 덜기 위해
            }

            public db.DicomStudy DicomStudy { get; set; }
            public List<Subitem> Subitems { get; set; }
        }
```

이 `StatusMessage`는 완성도를 높이기 위해 추후에 삭제 될 수 있습니다. (언어, 지역화, 표현방식 등의 이유로 client 에서 server 의 데이터를 이용해 구성하는 것이 알맞을 것 같습니다.)

**Comment by DPseol** [comment]
MARS 1016 버전 에서 수정. 파일 업으로드 UPDATE 글자 표시 확인.

**Comment by alkee-skia** [comment]
@DPseol > status 값은 UI 에 보여주고 있는 것 같지만, CT 데이터를 선택 했을 때 `/v2/Mars/ReviewStatus` 함수(API)를 호출하지는 않는 것 같습니다. 확인 부탁드립니다. 자세한 내용은 issue 본문을 참고해주세요.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by alkee-skia** [comment]
[MARS_v1940](https://github.com/alkee-skia/mars-processor/milestone/4)에서 수정내용 확인했습니다. 다만, Segmentation 화면에서 다시 CT 선택화면으로 되돌아 가는 경우에 review 상태가 업데이트 되고 있지 않는 것 같습니다.
우선순위는 높지 않기 때문에 별도 issue 에 추가하도록 하겠습니다.
