### ISSUE TITLE
Message, View panel 이 보여지지 않음

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#19]
toolbar 항목들 중 message, view 패널이 보여지고있지 않음.

![image](https://user-images.githubusercontent.com/49409100/96359333-97fc1980-114c-11eb-8d6e-eef3c88c0b40.png)

**Comment by DPseol** [comment]
Toolbar 관련 테스트 문제로 잠시 비워두었습니다. 추가하여 드리겠습니다.

**Comment by Dalaway** [comment]
![11](https://user-images.githubusercontent.com/67160138/96963301-6667c180-1543-11eb-992b-325236054878.PNG)
Message View, View Control 추가 확인하였습니다.
