### ISSUE TITLE
CT series 의 fold 아이콘 클릭으로 펼처짐/닫힘 기능하도록

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#2]
study-series 목록에서 study 의 double click 으로 펼침/접힘 동작이 이루어지고 있습니다만, series 를 더블클릭하게되면 Segmentation 상태로 진입(다운로드>로딩)하게 되어 실수로 선택하는 경우 부담이 상당합니다.

아이콘을 이용한 클릭(single click)만으로 study-series 의 펼침-접힘이 동작하면 좋겠습니다.

![image](https://user-images.githubusercontent.com/49409100/93842503-27d7b080-fcd2-11ea-8982-f6008754a9c3.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1962 이후 버전에서 확인 가능합니다.

**Comment by alkee-skia** [comment]
[MARS_v1978](https://github.com/alkee-skia/mars-processor/milestone/6) 에서 수정된 것을 확인했습니다.
