### ISSUE TITLE
Create skin, Create Lesion 제거

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#20]
Segmentation panel 에 `create skin`, `create lesion` 버튼 제거. 

테스트를 위한 버튼이라면 `TestControl`(data.ini) 설정을 통해 저희가 테스트할 때에는 없도록 할 필요가 있습니다.

해당 Mesh 를 생성하는 인터페이스 인 것으로 여겨지는데, 직관적이지 못합니다. Mask 를 생성(segmentation)하는 것으로 오해하기 쉽고 잘못 선택하였을 때 부담(processing 시간 등)이 너무 큽니다.

요구사항과 같이 **AR confirm 이 될 때 자동 생성(변경된 경우)**하는 방향이 좋겠습니다.
혹은 별도의 AR toobar panel 을 만들어 정보를 보여주는 방법이 있겠으나, 이 또한 AR confirm 을 통해 만들어진 mesh 를 확인해야한다는 점에서 불편한 ui 일 것 같습니다.

![image](https://user-images.githubusercontent.com/49409100/96359436-d6460880-114d-11eb-92f4-f50ffb050f17.png)

**Comment by jhpark-rs** [comment]
저 두 버튼은 test용이며, 정확히는 create skin/lesion mesh 입니다.
mesh 생성에는 시간이 많이 소요되는데, 
탭을 넘길때(AR Confirm 선택시) 실행되면 사용자들이 영문을 모르고 기다리는 상황이 발생할 것 같아 명시적으로 버튼을 만드는게 어떨까 생각해봤습니다. 
또한, skin과 lesion은 취급 방법이 동일하지 않으므로 분리하는 쪽을 추천합니다.
이점에 대해서도 고민해보시고, 결정해주시면 그대로 구현하겠습니다.

**Comment by alkee-skia** [comment]
취급 방법이 동일하지 않다는 것은 개발적인 측면일 것 같고, 사용자는 segmentation 완료 후 결과물 확인을 하는 커다란 flow 만 알도록 하고 싶습니다.

processing 의 진행상황을 확인하는 단계(progess)가 존재하기때문에 영문을 모르지는 않을 것 같습니다. skin 의 processing 이 오래걸리기는 하나, mask 가 변경되지 않으면 다시 processing 하지 않도록 해 기다리는 시간은 최초 1회로 한정할 수 있을것 같습니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![1](https://user-images.githubusercontent.com/67160138/96963471-a75fd600-1543-11eb-828c-b11b733494da.PNG)
Create skin, Create Lesion 제거 확인하였습니다.
