### ISSUE TITLE
panel 순서 변경 및 필수적이지 않은 요소 제거

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#21]
toolbar **panel 의 순서**를 아래와 같이 변경해주세요.

 1. Message
 2. View
 3. Segmentaion
 4. Tools
 5. VR

 또한,  필수적이지 않은 **아래 내용을 제거**하고 추후에 필요한 경우 완성도를 높여 추가할 수 있도록 해주세요.

 * Capture & Record panel
 * Tools panel 내 아래 항목(measurement 도구만 유지)
    - Annotation pen
    - Annotation note
    - Skulpt 관련

![image](https://user-images.githubusercontent.com/49409100/96359640-f8d92100-114f-11eb-9cec-e6fc0e6aace9.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![panel](https://user-images.githubusercontent.com/67160138/96964233-11c54600-1545-11eb-9a0e-206b511ddf84.PNG)
Panel 순서 변경 및 불필요한 요소(Capture&Record, Annotation, Sculpt) 제거 확인하였습니다.
