### ISSUE TITLE
system menu 에 지원하지 않을 기능/항목 제거

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#22]
CT segmentation 상태에서 system menu 의 항목 중 아래 항목을 제거해주세요.

개발환경을 위해 필요한 기능이라면 Data.ini 의 `TestControl` 설정을 통해 제거되도록 해주세요.

 * Open DICOM file
 * STL Export

![image](https://user-images.githubusercontent.com/49409100/96359685-97658200-1150-11eb-969b-76aeb165e26e.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![menu](https://user-images.githubusercontent.com/67160138/96964473-75e80a00-1545-11eb-83b9-c5135dda4005.png)
메뉴 수정 확인하였습니다.
