### ISSUE TITLE
Settings 에 지원하지 않을 요소 제거

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#23]
Settings dialog 에 아래 요소 제거

  * Language ; 제거하지않고 disable 하는 경우, 영문설정(고정)에서 "미국" 이 아닌 `en-US`(American English) 나 `English` 와 같이 한국어로 표기되지 않도록 해야합니다. (제거하는 편을 더 선호)
  * Capture & Record path (#21)

![image](https://user-images.githubusercontent.com/49409100/96359964-515ded80-1153-11eb-922b-f29bc63d52e2.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![setting](https://user-images.githubusercontent.com/67160138/96964159-f0fcf080-1544-11eb-94e2-5083e3036c0e.png)
Setting 수정 확인하였습니다.
