### ISSUE TITLE
segmentation(brush, eraser, livewire 및 magicwand) preview

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#25]
segmentation 이 완료된 후의 모양은 brush-eraser 및 포토샵 등으로 어느정도 문서화에 필요한 이미지를 만들어 낼 수 있으나, preview 의 경우 아직 어떤 방식으로 화면에 보여지는지 알 수 없습니다.

preview 의 우선구현 또는 해당 장면을 구성할 수 있는 가이드가 필요합니다.

**Comment by jhpark-rs** [comment]
어떤 preview를 말씀하시는지 잘 모르겠습니다.
필요한걸 그려서 주시면 좋겠습니다.

**Comment by alkee-skia** [comment]
@jhpark-rs  magic wand 사용 시 mouse over 된 위치에 대한 segmentation 될 영역(2D)을 미리 표시(클릭으로 mask 반영 전) 하는 preview 입니다.

xelis magic wand 의 경우 밝은 색으로 해당영역 보여짐  ; https://photos.google.com/share/AF1QipN6PJe07oBFKO4p8vTAWl29Wl5ccRPl-DwYj09RmxVvv0a4EuDHg2br48cO5uzOew/photo/AF1QipOqoi3rRzf6_1AGmO2RiGxlF5PE_Dp4IQBXpe1j?key=WmRqQkRWaURuYkR2YWxXM3M5dkRjLW15V1Z2X2xn

3d slicer 의 경우 노란색의 외곽선으로 해당영역 보여짐 ; https://photos.google.com/share/AF1QipN6PJe07oBFKO4p8vTAWl29Wl5ccRPl-DwYj09RmxVvv0a4EuDHg2br48cO5uzOew/photo/AF1QipNPi7TUy9IWLkNY15q3UNatv7yy2nNmkMtUecPi?key=WmRqQkRWaURuYkR2YWxXM3M5dkRjLW15V1Z2X2xn

**Comment by jhpark-rs** [comment]
segmentation 전체가 아니라, magic wand에만 해당되는 내용인 것 같습니다.
현재 숭실대 모듈에서 2D mask를 채워서 반환 하니, preview는 xelis와 비슷한 모습이 될 것 같습니다.
따라서, preview나 결과 영상이나 똑같을 것 같은데 "해당 장면을 구성할 수 있는 가이드"가 왜 별도로 필요한지 모르겠습니다.
우선순위 정해주시면 감사하겠습니다.

**Comment by alkee-skia** [comment]
@jhpark-rs preview 와 결과 영상이 같은 경우는 **올바른 위치를 선택했을 때 뿐**입니다. 올바른 위치 및 크기(parameter)를 선택했는지 확인하기 위해서 magicwand 뿐 아니라 **brush 및 eraser 에서도 마찬가지로 보여져야**합니다. preview 가 보이지 않는 상태에서는 선택하고 undo 하는 과정을 상당히 많이 겪어 몹시 불편합니다. [3d slicer](https://www.slicer.org/)(상용이 아니기에 최소한의 편의성)를 이용해 간단한 데이터를 직접 segmentation 해보신다면, 이와같은 내용 이해에 상당히 도움이 될 것이라고 생각됩니다. 이는 필수 요소이고 **우선순위가 높습니다.**

**Comment by jhpark-rs** [comment]
필요하다는건 알겠는데 
"preview 의 우선구현 또는 해당 장면을 구성할 수 있는 가이드" 에서 뒷부분이 뭔지 모르겠다는 의미입니다

**Comment by alkee-skia** [comment]
>"preview 의 우선구현 또는 해당 장면을 구성할 수 있는 가이드" 에서 뒷부분이 뭔지 모르겠다는 의미입니다

아.. **구현에 시간이 오래 걸리는 경우** 저희가 문서작업을 우선 진행해야하기 때문에, preview 의 모양이나 색 등 저희가 임의로 이미지 편집을 통해서라도 preview 가 동작하는 모습을 만들어내야하기 때문에, 어떤 식으로 구현이 될 것인지 정보가 필요하다는 의미입니다.

**Comment by alkee-skia** [comment]
> segmentation 전체가 아니라, magic wand에만 해당되는 내용인 것 같습니다.

brush 와 eraser 에도 해당합니다.  단순한 원형이지만 필요하시다면 스크린샷이나 동영상을 첨부하도록 하겠습니다.

**Comment by jhpark-rs** [comment]
segmentation 부분은 요구사항이 반영된 숭실대 라이브러리를 받고 진행하겠습니다.

**Comment by jhpark-rs** [comment]
**v1987**에서 기능 추가 하였습니다.

**Comment by Dalaway** [comment]
![aa](https://user-images.githubusercontent.com/67160138/101883081-1c619a80-3bda-11eb-99e5-6da4f9946bc1.PNG)
Preview 추가 확인하였습니다.

**Comment by Dalaway** [comment]
![MagicWandPreview](https://user-images.githubusercontent.com/67160138/101884855-a6aafe00-3bdc-11eb-9ee2-59f506d0298f.png)
![Pen,Erase Preview](https://user-images.githubusercontent.com/67160138/101884861-a9a5ee80-3bdc-11eb-9785-39ef25e046c1.png)
Magic Wand Preview 확인하였습니다.
다만 Brush와 Erase는 클릭후 드래그 상황에서만 Preview가 확인되어, 드래그 이전에는 어떻게 분할이 될지 알기 어렵습니다.
Magic Wand는 클릭 전에도 Preview가 잘 나타나지만, Brush와 Eraser는 그렇지 않은 것 같습니다.
[동영상](https://drive.google.com/file/d/1GBdZfba-pSygrXoWLfRBZy9b5PxAynDk/view?usp=sharing)과 같이 클릭 전에도 Brush와 Eraser의 Preview가 보이는 쪽으로 수정되었으면 합니다.

**Comment by jhpark-rs** [comment]
**v1990** 이후 버전에서 Brush/Erase 기능에서 drag 이전, L-button 클릭만 해도 preview 기능 실행됩니다.

**Comment by alkee-skia** [comment]
v1993 에서 확인했습니다만, 저희가 기대했던 것은 click 이전에 click 을 __시작할 위치를 결정하는데 도움__ 받을 수 있도록, Brush/Erase 를 선택하기만 해도 brush 의 영역이 나타나는 것이었습니다. 

[동영상 예시 참고](https://drive.google.com/file/d/1hT0Z9OSZKTvnrKTtcXeVjpoaMlP1lIpy/view?usp=sharing)

**Comment by Dalaway** [comment]
Segmentation Preview 확인하였습니다.
