### ISSUE TITLE
segmentation mask 가 반투명하게

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#26]
MPR view 에서 표시된 segmentation mask 가 너무 불투명해 원하는 영역을 알맞게 지정했는지 확인하고 수정하기 불편합니다. (특히 erase 시)

segmentation mask 가 반투명해 CT intensity 정보가 어느정도 나타나야합니다.

(3d slicer 의 예)
![3d slicer segmentation mask](https://blog.kitware.com/wp-content/uploads/2019/01/xslicer-4.10.1-segmentation-masking-feature-grow-from-seed-effect-1024x543.jpeg.pagespeed.ic.t9czQ2oYDh.webp)

**Comment by jhpark-rs** [comment]
저도 '반투명'과 '불투명' 사이에서 고민 해봤는데, 
lesion이란게 실제로는 손톱 정도 크기일 것으로 생각하는데, 그걸 반투명하게 표현하면 시인성이 떨어질 것 같아 불투명으로 결정하였습니다.
수정에 큰 부담은 없으니, 우선순위 정해서 처리하면 되겠습니다.

**Comment by alkee-skia** [comment]
segmentation 영역과 intensity 정보를 함께 확인할 수 있는 수준에서의 시인성으로 반투명하게 그려져야합니다.

**Comment by jhpark-rs** [comment]
"segmentation 영역과 intensity 정보를 함께 확인할 수 있는 수준" 가이드 부탁드립니다.

**Comment by alkee-skia** [comment]
위 3D slicer 정도라고 생각하는데, 좀더 구체적인 정보를 원하신다면, 보내드렸던 데이터중에 하나를 이용해 예시 이미지를 만들어 드리도록 하겠습니다.

**Comment by jhpark-rs** [comment]
연조직, 가능하면 실제로 가슴 lesion 등 좀 더 좁은 범위에 적용해보시고, 
RGBA값을 어떤 식으로 할당하면 좋을지 가이드 부탁드립니다.
제가 임의로 구현하면 결과가 만족스럽지 못할 것 같습니다.

**Comment by alkee-skia** [comment]
RGB 값은 원래 지정한 mask 의 색상이 될 것이라 alpha 만 조절 할 것이라고 생각됩니다.
`data.ini` 등에 alpha 를 조절해 볼 수 있는 설정이 있다면 저희가 직접 해보면서 알맞은 값을 찾을 수 있을 것 같습니다.

3d slicer 에서 병변을 분할한 화면을 포토샵등으로 최대한 비슷해 보이는 alpha 를 찾아 첨부해보도록 하겠습니다.

**Comment by jhpark-rs** [comment]
시인성을 높이기 위해서 원색을 많이 사용하였습니다.
제가 보기에도 전문적인 느낌이 부족해서 색상은 어차피 스키아에서 지정해주실 것으로 기대하였습니다.
이참에 skin 및 lesion에 대한 색상 지정도 부탁드립니다.

**Comment by alkee-skia** [comment]
> 이참에 skin 및 lesion에 대한 색상 지정도 부탁드립니다.

이부분도 별도의 설정으로 저희가 조절해 볼 수 있도록 해주시는 것은 어떨까요?

**Comment by jhpark-rs** [comment]
불가능한건 없지만, UI 작성에 품이 많이 듭니다.
우선순위를 정해주세요.

**Comment by alkee-skia** [comment]
> 불가능한건 없지만, UI 작성에 품이 많이 듭니다.

사용자가 설정할 내용이 아니기 때문에, 별도의 UI 없이 설정파일(`data.ini` 같은?)에서 설정할 수 있다면 UI 작성을 고민할 필요는 없지 않을까요?

> 우선순위를 정해주세요.

현재로서의 최우선순위는 10월 말 까지 임상시험계획서의 모든 내용을 채워넣는 것입니다. 그래서 개발시간에 어려움이 있으신 부분들은 가능일정을 말씀해 주셔야 그 우선순위를 알려드릴 수 있을것 입니다. 그래서 이미지 편집을 해서라도 문서화를 할 수 있을 것 같은 부분을은 issue 에서 별도 표기(priority tag 제거)하였습니다. 누차 말씀 드렸듯이 일단, 임상시에 변화가 적은 수준에서 문서화가 가능한 화면만이라도 있으면 됩니다.

**Comment by alkee-skia** [comment]
@jhpark-rs  3d slicer 의 투명도(실제로는 opacity 값) 기본값은 0.5 로 확인됩니다. 3d slicer 와 같이 _외곽선을 함께 지원하는 경우_ 0.3 정도가 시인성이 좋아보이지만, 저희가 현재 지원하지 못하기 때문에 **0.5 를 기본값**으로 해주시면 좋겠습니다. 가능하다면 설정(별도 UI 없이 `ini` 등)을 통해 변경해 테스트해보기 쉽게 해주시면 좋겠습니다.

테스트 정보 : [masksample.zip](https://github.com/alkee-skia/mars-processor/files/5406048/masksample.zip)

**Comment by jhpark-rs** [comment]
수정완료. (alpha:0.5 blending)

**Comment by Dalaway** [comment]
![반투명](https://user-images.githubusercontent.com/67160138/96963720-19d0b600-1544-11eb-9094-117daf9fdf16.PNG)
Mask 반투명 수정 확인하였습니다.
