### ISSUE TITLE
VR preset 선택시 크래시

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#28]
Toolbar VR 패널의 preset 중 세번째 또는 네번째 preset 선택시 프로그램이 크래시됩니다.

![image](https://user-images.githubusercontent.com/49409100/96412428-1d52fd00-1225-11eb-85ae-f53cb7d79008.png)

**Comment by jhpark-rs** [comment]
수정 완료

**Comment by Dalaway** [comment]
![VR Crash(1)](https://user-images.githubusercontent.com/67160138/96963622-e4c46380-1543-11eb-9843-d6b58081d0ba.PNG)
![VR Crash(2)](https://user-images.githubusercontent.com/67160138/96963617-e3933680-1543-11eb-8ca3-069ae0c8a322.PNG)
크래시 수정 확인하였습니다.
