### ISSUE TITLE
Fileinfo 의 resolution 과 diameter(?) 표시 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#29]
File info 의 resolution (pixel) 과 diameter(? 구형이 아니라 어울리는것 같지는 않습니다만..)

값이 바뀌어있는 것 같습니다.

![image](https://user-images.githubusercontent.com/49409100/96429727-3f0bae80-123c-11eb-9eb8-573b6dcee316.png)

**Comment by jhpark-rs** [comment]
resolution은 일반적으로 쓰이는 표현으로 각각 pixel/slice spacing 값에 해당합니다.
Diameter는 Dimension을 잘못 표기한 것으로, 수정하였습니다.

**Comment by Dalaway** [comment]
![dimension](https://user-images.githubusercontent.com/67160138/96963892-6ddb9a80-1544-11eb-90a1-f07a4cb9d958.png)
Diameter -> Dimension 수정 확인하였습니다.

**Comment by alkee-skia** [comment]
[MARS_v1940](https://github.com/alkee-skia/mars-processor/milestone/4)에서 수정내용 확인했습니다
