### ISSUE TITLE
선택한 데이터가 아닌 데이터가 로드됨

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#3]
CT selection 에서 선택한 데이터가 아닌 데이터가 Segmentation 상태에서 나타남.

![image](https://user-images.githubusercontent.com/49409100/93842931-48ecd100-fcd3-11ea-8847-14707c34cd36.png)

![image](https://user-images.githubusercontent.com/49409100/93842937-4be7c180-fcd3-11ea-910c-37d5a233c8b2.png)

**Comment by DPseol** [comment]
재현 방법을 말해주세요. (비교 테스트 해볼수있는 상황)
원본 데이터 와 네트웍으로 받은 데이터의 비교 등이 있을거 같습니다.

하나의 폴더에 여러개의 Series 데이터가 있는경우 첫번째 Series를 읽어옵니다.
네트웍에서 Series 별로 나누어 데이터를 내려받을때 하나의 폴더에 하나의 시리즈만을 가져오는지도 확인해 봐야합니다.

데이터를 받은후 하나의 폴더에 하나의 Series가 있다는 가정하에서 해당되는 폴더를 읽어옵니다.

**Comment by alkee-skia** [comment]
@DPSeol

올바르지 않은 경로의 파일을 다운로드 하고있는 것 같습니다. 즉, 로컬 `C:\DICOMDownload` 에 저장되어있는 파일이, 해당 series 파일 목록의 파일들과 일치하지 않습니다.

예를들어 dicomSeries  ID 35 파일의 경우 http://my.alkee.net:40088/v2/Dicom/FileInSeries/35  에서 파일 목록을 얻을 수 있는데 로컬에 저장되어있는 파일은 서버에서 요구하는(파일목록) 파일들과 다릅니다.

![image](https://user-images.githubusercontent.com/49409100/96709133-3c908c80-13d5-11eb-9a45-c966fa1c9b7d.png)

**Comment by alkee-skia** [comment]
@DPseol 초대드린 github contributor 에 참여해주시고, 담당작업(issue)에 assign 해주시면(assignee 추가 또는 변경) 커멘트가 추가되거나 상태가 변경되는 경우 메일로 알람을 받아보실 수 있으니 참고해주세요

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by alkee-skia** [comment]
[MARS_v1940](https://github.com/alkee-skia/mars-processor/milestone/4)에서 수정내용 확인했습니다
