### ISSUE TITLE
VR clipping 이 동작하지 않음

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#32]
VR tool panel 의 clipping 설정이 동작하지 않고, 전혀 변화가 없음.

![image](https://user-images.githubusercontent.com/49409100/96546202-c9a7e880-12e4-11eb-8d9b-03cecbea62df.png)

**Comment by jhpark-rs** [comment]
현재 mask와 clipping 또는 sculpting 기능과 상충되는 부분이 있고,
해당 기능에 대한 필요성이 적어 삭제 합니다.

**Comment by alkee-skia** [comment]
clipping 기능을 삭제한다는 말씀이시죠?

issue close 는 보내주신 버전에서 내용이 확인되면 저희가 하도록 하겠습니다.

**Comment by Dalaway** [comment]
![clip](https://user-images.githubusercontent.com/67160138/96963993-9e233900-1544-11eb-8c84-f187ebbc9988.PNG)
clipping bar 삭제 확인하였습니다.
