### ISSUE TITLE
patient 정보에 birthdate 정보 표시

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#33]
환자정보(메뉴 항목의 `Patient information`)에서 date 가 불문명. 환자정보이므로 `Birthdate` 로 표기하고 환자의 생년월일을 알맞게 표기해주어야 합니다.

현재버전(MARS1016)까지는 원하는 환자를 로드할 수 없어(#3) 확인 어려우니, 이 이슈와 함께 수정되면 좋겠습니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![birthdate](https://user-images.githubusercontent.com/67160138/96963841-59979d80-1544-11eb-99a1-8b37108ab445.png)
birthdate 추가 확인하였습니다.
