### ISSUE TITLE
T-Local 버튼 나타남

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#34]
CT 선택 후 segmentation 화면에서 다시 CT 선택 화면으로 되돌아 가는 경우 아래와 같이 개발용 기능으로 보여지는 T-Local 버튼이 나타납니다.

![image](https://user-images.githubusercontent.com/49409100/97131174-cdc18380-1786-11eb-897a-5b8774a98dfa.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![캡처](https://user-images.githubusercontent.com/67160138/97555421-7425b700-1a1b-11eb-8c27-6ed1cfa5d525.PNG)

T-local 수정 확인하였습니다. (CT Selection 이후의 스크린샷입니다.)
