### ISSUE TITLE
다른 tool 선택으로 segmentation tool 이 유지되는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#36]
segmentation tool 을 선택한 후, 다른 tool(예 - ruler)을 선택하면 툴 선택이 바로 반영되지 않다가, 화면 scroll 등 다시 그려지는 상황에 상태 업데이트가 됩니다. 이 때 parameter(detail) setting 의 일부는 그대로 남아 보여집니다.

반대의 경우(ruler 등 tool 이 선택되어있는 상테에서 segmentation 의 도구 선택)에도 이전 선택한 상태가 남아있습니다.

| segmentation 중 ruler 선택 | 화면이 갱신(scroll 등)된 후 |
|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/97134270-25b0b800-1790-11eb-858f-55df632c2812.png)| ![image](https://user-images.githubusercontent.com/49409100/97134262-1f224080-1790-11eb-9c1a-b7819b17bed7.png) |

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![a](https://user-images.githubusercontent.com/67160138/97556418-cca98400-1a1c-11eb-8319-2267fe842812.png)
툴 선택 즉시 반영 확인하였습니다.
