### ISSUE TITLE
Undo 에 의해 view 가 변경되는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#37]
view 를 변경하며 segmentation 중, undo 를 하게되면 mask 뿐 아니라 view 의 상태까지도 변경됩니다. undo-redo 는 mask 의 상태만을 변경해야합니다.

| 1. segmentation 선택 | 2. segmentation | 3. undo |
|----|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/97135225-141cdf80-1793-11eb-8d47-6aedf87d3fc7.png) | ![image](https://user-images.githubusercontent.com/49409100/97135228-15e6a300-1793-11eb-9ea8-aa2f3d1f68f2.png) | ![image](https://user-images.githubusercontent.com/49409100/97135233-1848fd00-1793-11eb-884a-657ab0d334b2.png) |

**Comment by jhpark-rs** [comment]
magic wand를 주로 사용하는 상황을 고려하여, 마지막 click point를 기억하고 해당 위치로 이동하는 기능입니다.
brush/erase 같은 경우는 하나의 point가 지정되지 않기때문에 일단 원점으로 이동하는 것으로 구현하였습니다.

해당 기능이 mask의 위치만 변경해야 하는 건 아닌것 같지만, 위치 이동 원치 않으시면 삭제 하겠습니다.

**Comment by alkee-skia** [comment]
조금 더 사용해보며 직접 lesion segmentation 을 해보면서 추가 피드백 드리도록 하겠습니다.

**Comment by jhpark-rs** [comment]
#59 이슈와 통합하여, undo/redo시 axis line 변경 기능을 제거하였습니다.
v2009 이후 확인할 수 있습니다.

**Comment by Dalaway** [comment]
v2014에서 #59 이슈 해결 확인하였습니다.
