### ISSUE TITLE
툴바의 위치설정(L/R) 변경후에 유지되지 않는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#38]
설정을 통해 툴바의 위치를 바꾸어(`Toolbar L/R`) 툴바가 오른쪽에 있는 경우, 프로그램을 재실행 되는 경우 툴바가 원래 위치로 되돌아갑니다. 마지막 상태가 유지되어야 합니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![1](https://user-images.githubusercontent.com/67160138/97555652-b64ef880-1a1b-11eb-8194-6f0c73689fad.PNG)
![s](https://user-images.githubusercontent.com/67160138/97555784-e72f2d80-1a1b-11eb-80ea-c87db1e0d110.PNG)

Toolbar L/R 수정 확인하였습니다. (Toolbar R 세팅 후 재부팅한 모습입니다.)
