### ISSUE TITLE
magic wand parameter 단위 설정 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#39]
magicwand segmentation API 의 `Radius` 의 입력단위는 pixel 이고 `ThRange` 의 입력단위는 HU 입니다.

![image](https://user-images.githubusercontent.com/49409100/97163642-4a268780-17c4-11eb-95cc-db0386b6e927.png)

ThRange 의 경우 `HU` 로 단위로 UI 에 표시해주시고, Radius 의 경우 해당 pixel 로 계산된 mm 단위(`pixelspacingX x pixelspacingY x sliceThickness` x pixel mm)로 표현해 주시면 좋겠습니다.

예) (0.76 x 0.76 x 2.00) resolution 의 series 인 경우 10 pixel  이라면 `(7.6 x 7.6 x 20.0) mm` 와 같이 표시

**Comment by jhpark-rs** [comment]
Radius의 경우, 축별 resolution이 상이 할 수 있으므로 현행대로 mm 단위로 표시하는게 맞습니다.
옆에 Grow/Shrink와 같이 옆에 pixel로 환산한 크기(10x10x5 pixels)를 표시하겠습니다.

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![제목 없음](https://user-images.githubusercontent.com/67160138/97556112-5442c300-1a1c-11eb-8191-f7fa5d93f8d1.png)
![d](https://user-images.githubusercontent.com/67160138/97556114-5573f000-1a1c-11eb-8616-8886acfdef1d.png)
수정 확인하였습니다.
