### ISSUE TITLE
버전표시에 서버 버전 표시

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#4]
버전표시에 클라이언트 버전만 표시되고있으나 서버 버전도 함께 표시되어야 합니다.
( `/v2/Status/Version` API 사용 : 예 : http://my.alkee.net:40088/v2/Status/Version )

![image](https://user-images.githubusercontent.com/49409100/93845471-e1874f00-fcdb-11ea-9263-f2b57904d865.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

- 버전정보가 수시로 변하지않는 전제로 처음 프로그램 열린후, 자동으로 리스트 가져올때 같이 버전 정보를 1번 가져옵니다.
- 처음 한번 가져온 문자로 계속 버전을 표시합니다.
- Server Ver 위의 MARS 버전 정보는 MARS 실행파일 같이 있는 VerInfo.ini 파일에서 버전을 읽어 표시합니다.

**Comment by Dalaway** [comment]
![ssa](https://user-images.githubusercontent.com/67160138/97556638-16926a00-1a1d-11eb-93ff-97fadb47b178.png)
Server Version 확인하였습니다.
