### ISSUE TITLE
Grow/Shrink parameter 단위 설정 문제 

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#40]
Grow/Shrink 의 경우 세부 입력값으로 StepSize 를 입력받는데, step size 및 변환된 크기 label 모두에 **단위가 표시되고  값 변경이 반영**되어야 합니다.

![image](https://user-images.githubusercontent.com/49409100/97164394-6545c700-17c5-11eb-8a4d-edc5b3704c55.png)

 * pixel(voxel )단위 입력을 받는 경우 해당 크기(mm)를 label 로 하단에 나타내 주거나
 * ~~mm 단위 입력을 받고 해당 크기의 pixel(voxel)의 개수를 label 로 하단에 나타내 주어야 합니다.~~(아래 3D slicer 의 예 - 참고용)

![image](https://user-images.githubusercontent.com/49409100/97165122-8ce95f00-17c6-11eb-9ac3-01748b5600a0.png)

실제 동작하는 방식은 pixel 단위가 될 것으로 보여지기 때문에, mm 단위의 부정확한 값을 입력하기보다 pixel 을 `StepSize` parameter 로 받고 추가정보에 resolution(mm) 표시를 해주시는 것이 좋아보이긴 합니다. (3D slicer 와 반대로 표현)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1946 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![dd](https://user-images.githubusercontent.com/67160138/97665887-d801bb80-1abf-11eb-9a2a-6a04c8bae2ec.png)

Parameter 수정 확인하였습니다.
