### ISSUE TITLE
segmentation 영역 끝 부분에서 mask 영역 색이 달라지는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#42]
VR 에서는 각각의 색의 영역으로 보여지지만 MPR 에 보여지는 segmentation mask 는 끝부분의 색이 변합니다.

| 6 | 5 | 4 | 3 | 2 | 1 |
|----|----|----|----|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/99174653-fe755700-274d-11eb-9881-3788689313a8.png) | ![image](https://user-images.githubusercontent.com/49409100/99174736-059c6500-274e-11eb-8d14-aa5851e9e21f.png) | ![image](https://user-images.githubusercontent.com/49409100/99174769-0a611900-274e-11eb-94d9-4465bc8f385f.png) | ![image](https://user-images.githubusercontent.com/49409100/99174845-1056fa00-274e-11eb-8ff4-7b6b1143adae.png) | ![image](https://user-images.githubusercontent.com/49409100/99174888-13ea8100-274e-11eb-999c-f603055063ee.png) | ![image](https://user-images.githubusercontent.com/49409100/99174916-15b44480-274e-11eb-9ed1-e274b2e6c5fb.png) |

**Comment by jhpark-rs** [comment]
기존 bit mask 방식은 작은 index일 수록 인접 index와 표현값(0x01, 0x02, 0x04, ...0x80)의 절대적 차이가 작기 때문에 interpolation을 동반한 sampling 과정에서 값이 잘못 읽히기가 쉽습니다. 
(현재 사용하는 hlsl fx_2_0 모델에서는 interpolation 없는 load 함수 지원하지 않음)

이에 **v1981**에서 각 lesion의 표현값 간격이 일정하도록 수정하고, 유사 load함수를 구현하여 **현상을 완화**시켰습니다.
각 lesion에 할당된 표현값은 아래와 같습니다.
(0x1F, 0x3F, ...0xFF)

**Comment by alkee-skia** [comment]
v1993 에서 수정내용을 확인했습니다.
