### ISSUE TITLE
Grow-shrink 시에 slice index 가 변경됨

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#44]
Brush 작업 이후에 grow-shrink 를 선택하고 실행하면, slice index 가 변경되어 원하지 않는 위치로 이동합니다.

| 작업 view | grow-shrink 툴 선택 | grow 실행 후 |
|----|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/99219170-6e074700-281f-11eb-9940-89419c2562bd.png) | ![image](https://user-images.githubusercontent.com/49409100/99219200-80818080-281f-11eb-8cab-3d06f9a77665.png) | ![image](https://user-images.githubusercontent.com/49409100/99219215-85decb00-281f-11eb-8bf2-de5b1256b4f7.png) |

**Comment by jhpark-rs** [comment]
grow/shrink 실행시 변경된 mass의 중심으로 이동하는 기능이었으나, 요청에 의해 **v1981에서** 삭제 하였습니다.

**Comment by Dalaway** [comment]
Slice Index 유지 확인하였습니다.
