### ISSUE TITLE
livewire 시작점을 취소할 수 없는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#46]
livewire 를 중지하고 다시시작하고자 하는 액션을 취할 수 없음.
모든 point 를 취소(우클릭)하거나 livewire 를 중지(UI button)하는 경우 처음부터 다시 시작할 수 있어야 할 것.

[발생상황 동영상](https://drive.google.com/file/d/17v4cMxb6BiRzcAOP46Eru_V37SOg_9Nk/view?usp=sharing)

**Comment by alkee-skia** [comment]
ESC 를 눌러 다시시작 할 수 있는 상황을 발견.

**Comment by jhpark-rs** [comment]
기존 ESC취소 기능에 더해, **v1981에서** 마우스 R클릭으로 시작점까지 삭제 가능하게 수정하였습니다.

**Comment by Dalaway** [comment]
esc 및 마우스 R클릭으로 Live Wire 취소 확인하였습니다.
