### ISSUE TITLE
livewire 사용 후 undo 하는 경우 slice 위치가 변경됨

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#47]
livewire tool 을 사용하고나서 undo 하는 경우 slice 위치가 변경되어 undo 를 사용하기가 너무 불편함.

[발생상황 동영상](https://drive.google.com/file/d/1BkwgoPBuSGMJPY9c4_p15vnd_XOwolv3/view?usp=sharing) 35초 쯤부터.

**Comment by jhpark-rs** [comment]
버그 수정 완료

**Comment by Dalaway** [comment]
버그 수정 확인하였습니다.
