### ISSUE TITLE
livewire 사용중 slice 이동 undo 명령등을 실행하면 이상동작

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#49]
이상동작을 막기 위해 livewire 사용 중 UNDO 나 slice 이동 등을 막아야 할 것.

**Comment by jhpark-rs** [comment]
**v1981에서** livewire 실행중 slice 이동 기능 차단하였습니다.
다음 버전에서 undo/redo 기능도 차단하겠습니다.

**Comment by Dalaway** [comment]
Slice 이동기능 차단 확인하였습니다. 
이후 Undo/Redo 기능 차단 확인 후 Issue Close하겠습니다.

**Comment by jhpark-rs** [comment]
**v1984**에서 livewire 실행중 undo/redo 기능도 차단하였습니다.
추가로 active lession 변경시에는 live wire 기능이 초기화 됩니다.

**Comment by Dalaway** [comment]
Undo/Redo 기능차단 확인하였습니다.
다만 기능 차단 과정에서 오류가 있었는지, Live Wire 이용 시 전혀 다른 곳에 포인트가 지정됩니다.
별도로 [이슈](https://github.com/alkee-skia/mars-processor/issues/54) 생성해 두었습니다.
