### ISSUE TITLE
최초 실행시 frame 의 일부만 출력됨

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#5]
최초 실행시 frame 만 표시되고, resize 이후에 올바르게 표시됨. 이후 다시 실행하더라도 size 조절한적이 없다면 같은 상태이고, size 조절한적이 있다면 올바르게 표현됨. 최초 실행시에도 올바르게 표시되도록 해주세요.
(혹시 windows registry 를 사용하는 부분이 있다면, 가능하면 별도 설정파일에 이를 포함하면 좋겠습니다.)

![image](https://user-images.githubusercontent.com/49409100/93846066-f2d15b00-fcdd-11ea-81ed-8b511d5fa92c.png)

**Comment by alkee-skia** [comment]
Windows 10 pro 또는 enterprise 버전을 사용하신다면 [Windows sandbox](https://techcommunity.microsoft.com/t5/windows-kernel-internals/windows-sandbox/ba-p/301849)이용해 쉽게 확인하실 수 있습니다.

**Comment by DPseol** [comment]
똑같은 재현 상황이 안나와 의심되는 부분을 수정하였습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
Windows Sandbox에서 테스트하여 정상 출력 확인하였습니다.
