### ISSUE TITLE
AR confirm 이후 다시 segmentation 할 수 없음

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#51]
segmentation 중에 AR confirm 하면, 다시 segmentation 으로 돌아가더라도 이전 mask 들이 더이상 보여지지 않음.

AR confirm 이후 잘못된 점을 발견하면 segmentation 을 다시 해서 수정할 수 있어야 함.

**Comment by jhpark-rs** [comment]
관련된 기능이 많아, 좀 더 확인이 필요하지만 기본적인 segmentation 기능이 실행되는 것은 확인하였습니다. 
v2014 이후에서 확인 가능합니다.

**Comment by Dalaway** [comment]
AR Confirm 이후에도 다시 Segmentation 가능해진 상황 확인하였습니다.
