### ISSUE TITLE
Segmentation 문제 확인이 어려움

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#52]
숭실대 모듈에서 문제가 있는지, 다른 원인이 문제인지 확인하기가 어려움. 따라서, Segmentation 관련 입력값에 대한 충분한 로그가 필요해 보임.  `data.ini` 의 `[Log] Level=4` 인 경우 아래와 같은 항목들이 로그에 저장될 필요가 있음.

아래의 정보들이 기록된다면 숭실대쪽에서 MARS Breast 를 이용해 문제확인하고, 개선이 가능할 것.

 * 로드된 data 정보 ; patient id, study id, 및 series number)
 * Livewire ; 사용한 SeedSliceIdx, SeedPoints, parameter(DepthRadius, ThRange), 결과 SegmentRegionInfo
 * Magicwand ; 입력위치(SegmentPoint3D), parameter(Radius, ThRange), 결과 SegmentRegionInfo

**Comment by jhpark-rs** [comment]
**v1984** log 기능 추가
- [2020-12-11 10:07 S:25 MS:923][I] DataManager::Patient ID(AN_ID_20191001080708), Study Desc(Thorax^01_CHEST_ROUTINE_POST40 (Adult)), Series ID(5)
- [2020-12-11 10:07 S:25 MS:924][I] DataManager::Data info : modal(1612397536), width(162), height(512), depth(512)
- [2020-12-11 10:07 S:31 MS:979][I] LiveWire::Init : volume(22060210), width(162), height(512), depth(512), error code(0)
- [2020-12-11 10:07 S:32 MS:098][I] LiveWire::SetSeedSliceIdx : index(256), error code(0)
- [2020-12-11 10:07 S:32 MS:184][I] LiveWire::AddSeedpoint : seed(93, 310), error code(0)
- [2020-12-11 10:07 S:47 MS:605][I] LiveWire::CheckNGetMask : mask(17F459A8), segmented region(87, 310, 255, 18, 34, 3), value(63), error code(0)
- [2020-12-11 13:11 S:36 MS:097][I] MagicWand::Init : volume(17D959A8), width(162), height(512), depth(512), error code(0)
- [2020-12-11 13:11 S:36 MS:097][I] MagicWand::SetThRange : HU range(40), error code(0)
- [2020-12-11 13:11 S:37 MS:351][I] MagicWand::SetRadius : radius(5, 15, 15), error code(0)
- [2020-12-11 13:11 S:38 MS:969][I] MagicWand::Segmentation : seed(93, 328, 256), mask(17d961e8), value(63), region(88, 313, 241, 11, 30, 31), error code(0)

**Comment by alkee-skia** [comment]
logging 확인되었으며, 추가 요청이 있을 경우 별도 issue 로 남기도록 하겠습니다.
