### ISSUE TITLE
mask value 변경 후 mesh generation 이상

### ISSUE THREAD

**Issue by jhpark-rs** [alkee-skia/mars-processor#53]
종전 bit mask 방식으로 lesion 가장자리의 색번짐 현상을 해결하기 어려워 byte value를 사용하는 방식으로 수정하였습니다.
수정 후 GetMesh(...) 함수의 6번째 인자 inTargetByteValue 가 작은 값을 갖는 값을 경우, 
그보다 큰 값을 갖는 lesion 영역까지 모두 포함한 mesh를 생성하는 것을 확인하였습니다.
- mesh 01 : 0x3F
- mesh 05 : 0xBF
- mesh 07 : 0xFF
![image](https://user-images.githubusercontent.com/71689313/101704247-a705a500-3ac7-11eb-8979-831ea1c08200.png)
![image](https://user-images.githubusercontent.com/71689313/101704274-b1c03a00-3ac7-11eb-9a3c-c0f7e61b22fc.png)
![image](https://user-images.githubusercontent.com/71689313/101704291-bc7acf00-3ac7-11eb-944d-caecde929dbb.png)

**Comment by alkee-skia** [comment]
segmentation volume source 의 bit-mask 를 이용하기 때문이 아닐까 합니다.
source mask 의 해당 bit 가 채워져있는 경우 함께 extract 되기 때문에, 입력값으로 `1 << lesionNumber` 와 같이 사용하신다면 겹쳐(중복) 생성되는 것은 피할 수 있지 않을 까 싶습니다.(테스트 코드에서도 그와같이 사용했었습니다.) 이 문제가 아니라면, 숭실대와 함께 이야기 해보아야 할 것 같습니다.

```cpp
	unsigned char ucByteValue = 1<<5;
// ...

// test mask volume 생성
	for(int row=0; row<iHeight; row++)
	{
		for(int col=0; col<iWidth; col++)
		{
			int iSIdx = row*imgData->widthStep + col;
			int iDIdx = row*iWidth + col;
			unsigned char* pucSVal = (unsigned char*)(imgData->imageData + iSIdx);
			if(pucSVal[0] != 0)
				ppucVolData[idx][iDIdx] |= ucByteValue;
		}
	}

// ...

// mesh 얻기
pCIMeshGen->GetMesh(CiMesh, bInterpolationFlag, bSmoothingFlag, bDecimationFlag, bMeterScaleFlag, ucByteValue, &errNo);

```

**Comment by jhpark-rs** [comment]
> segmentation volume source 의 bit-mask 를 이용하기 때문이 아닐까 합니다.

저도 그렇게 예상합니다.
다시 예전 처럼 bit mask 형태로 변환하려면 실행 시간도 추가되고, 불필요한 메모리 사용도 생기니
이 건은 개발 편의상 숭실대 쪽에 수정 요청해주시면 좋겠습니다.

**Comment by jhpark-rs** [comment]
**v1989**에서 201211_MeshGen_API 적용하여 문제 해결하였습니다.

**Comment by Dalaway** [comment]
![Lesion 1 to 7](https://user-images.githubusercontent.com/67160138/102184521-ef232e00-3ef2-11eb-9040-4f4ba8beaca5.PNG)
![3D Lesion Mesh](https://user-images.githubusercontent.com/67160138/102184527-f0ecf180-3ef2-11eb-892a-0da9d98ff131.PNG)
![lesion3](https://user-images.githubusercontent.com/67160138/102184530-f1858800-3ef2-11eb-873b-7710248e5d04.PNG)

Lesion 1부터 7까지 3D 뷰어로 확인 결과 정상 분리되어 있습니다.
수정 확인하였습니다.
