### ISSUE TITLE
Live-Wire 툴 사용 시 전혀 다른 곳에 Point가 지정

### ISSUE THREAD

**Issue by Dalaway** [alkee-skia/mars-processor#54]
![제목 없음](https://user-images.githubusercontent.com/67160138/101737127-cd4b3500-3b07-11eb-9ab4-e08ada575937.png)

v1984에서 Live-Wire 툴을 사용할 시 클릭한 지점과 전혀 다른 곳에 Point가 지정되는 오류가 발생

**Comment by jhpark-rs** [comment]
**v1986**에서 수정하였습니다.

**Comment by Dalaway** [comment]
v1987에서 Click Point 수정 확인하였습니다.
