### ISSUE TITLE
skin marker 의 mesh 가 생성되지 않음

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#55]
uplaod 하기위해 AR confirm 탭으로 이동했을 때, 업로드에 필요한 파일들 중 skin marker 를 발견할 수 없었음.

전달해 드렸던 [SkinMarkerGen](https://drive.google.com/file/d/1s8BCVWDUU5-Dcy07FqMiuuu50FlwxJyL/view?usp=sharing)을 이용해, Skin mesh(`.obj`)로부터 skin marker 파일들(`.obj`)을 생성해 업로드해야 합니다.

테스트한 데이터 : `AN_ID_20190529080316`

<img src="https://user-images.githubusercontent.com/49409100/102036802-261c1580-3e07-11eb-973e-7483fe4befc2.png" alt="screenshot" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="400"/>

| 필요 데이터 | 확인 | 필요 |
|----|----|----|
| images(`.png`) | V |  |
| skin(`.obj`) | V |  |
| **lesion(`.obj`)** | V | |
| **skin marker(`.obj`)** | | V |

**Comment by alkee-skia** [comment]
### SkinMarker 생성 참고 정보
  * [20201124-SkinMarkerGen-win32-mt-dll.zip](https://drive.google.com/file/d/1s8BCVWDUU5-Dcy07FqMiuuu50FlwxJyL/view?usp=sharing)

### 기대하는 sample (MARS app 에서 사용하는 파일) 참고

  * https://drive.google.com/file/d/1EsmfFyyN2PRfZGLoj4YVciE_IJftoya2/view?usp=sharing
  * https://drive.google.com/file/d/11nY5TgZh8-TDWqVrpoLIbX-JrTST_5xR/view?usp=sharing
  * https://drive.google.com/file/d/1RJzQldFcGKb8j7waAfxehYt5ESm1OT8L/view?usp=sharing
  * https://drive.google.com/file/d/1Vq9Wcr0R25odHCQz5JubT-7WniYA_OR5/view?usp=sharing

**Comment by alkee-skia** [comment]
업로드 불가 문제(#45)의 원인이 아닐는지 의심

**Comment by alkee-skia** [comment]
v1993 에서 여전히 발생하고 있으며, `%AppData%\Roaming\MarsData\Upload\MARKER` 이 비어있습니다.

[20201215.log 다운로드](https://github.com/alkee-skia/mars-processor/files/5693741/20201215.log)

제 자리에서 발생한 로그 입니다.

```
[2020-12-15 15:17 S:24 MS:191][E] [RBS]CSegmentationManager:CreateSkinMarker [2020-12-15 15:17 S:24 MS:195][S] [RBS]ThreadARFileCreate : Marker Create Return Val ( -1 ) Param 1 : C:\Users\alkee\AppData\Roaming\MarsData\Upload\SKIN\skin.obj, Param 2 : C:\Users\alkee\AppData\Roaming\MarsData\Upload\MARKER
```
와 같은데,  저희가 드린 API(`ExportSkinMarker`)의 반환은 -1 이 있을 수 없어 이상합니다.

발생하는 상황을 추가 기록하도록 하겠습니다.

**Comment by Dalaway** [comment]
v1993에서도 아직 skin marker가 생성되지 않습니다.
해당 로그를 첨부해 드립니다.
[Marker 미생성 Log Level 4.txt](https://github.com/alkee-skia/mars-processor/files/5693826/Marker.Log.Level.4.txt)

**Comment by alkee-skia** [comment]
실행경로에 `skinmarker.targets.json` 파일을 넣고, 업로드에 성공하는 UI 까지는 확인하였습니다.

서버에 업로드된 데이터확인 후 issue close 하도록 하겠습니다.
