### ISSUE TITLE
png 로 변환된 image 의 배경이 제거되지 않았음

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#56]
`.png` 로 변환된 이미지는 skin 분할된 정보에 따라 몸통 외부는 투명하게(alpha) 설정되어야 합니다.

[예시(sample) 파일들](https://github.com/alkee-skia/mars-processor/issues/55#issuecomment-744127946)에 포함된 CT image 참고

| 기대하는 image(with alpha) | 생성된 이미지 |
|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/102034089-7e9be480-3e00-11eb-8c36-cd46b8f033ca.png) | ![image](https://user-images.githubusercontent.com/49409100/102034071-7479e600-3e00-11eb-8618-c577cfc459d7.png) |

**Comment by jhpark-rs** [comment]
**v1990**에서 수정 하였습니다.

**Comment by Dalaway** [comment]
![ct2png069](https://user-images.githubusercontent.com/67160138/102179801-1fff6500-3eeb-11eb-84d3-599cc3b9140e.png)
배경 제거 확인하였습니다.
