### ISSUE TITLE
png 로 변환된 이미지의 방향이 달라짐

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#57]
AR confirm 단계에서 생성되는 `.png` 의 상하(A-P)방향이 뒤집혀 생성됨.

현재 MARS app(iPad) 에서 skin mesh 와 `.png` 이미지 pixel 이 정렬되어있다는 가정을 두고 개발되었기 때문에, dicom 원본(original AXIAL 기준)의 이미지가 그대로 출력되어야 함.

문제예시 : AN_ID_20190529080316, CT Image 67

![image](https://user-images.githubusercontent.com/49409100/102034709-11894e80-3e02-11eb-8613-8bf0f42b8dd7.png)

**Comment by jhpark-rs** [comment]
bitmap 생성 과정에서 상하 반전 보정하는 코드가 누락되었습니다.
**v1990**에서 수정하였습니다.

**Comment by Dalaway** [comment]
![ct2png067](https://user-images.githubusercontent.com/67160138/102179850-37d6e900-3eeb-11eb-98ef-f0774198fbf1.png)
상하 반전 확인하였습니다.
