### ISSUE TITLE
2D segmentation 지원 이상문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#58]
Segmentation(brush, eraser, livewire, magicwand)을 2D 를 선택한채로 진행했을 때에도, 

다른 slice 에 영향이 미치는 3D 로 동작하는 문제.

모든 segmentation 기능에 적용 필요.

grow/shrink 의 경우, 어느 이미지를 대상으로 하는지 정하기 쉽지 않으므로 2D-3D 선택을 제외하거나 2D 의 경우 plane 을 선택하도록 해야할 듯.

| 수행한 위치 | 주변위치1 | 주변위치 2 |
|----|----|----|
| ![image](https://user-images.githubusercontent.com/49409100/102311977-29eb9b80-3fb1-11eb-9632-65624c376805.png) | ![image](https://user-images.githubusercontent.com/49409100/102311986-2e17b900-3fb1-11eb-8e97-48bf99822a42.png) | ![image](https://user-images.githubusercontent.com/49409100/102311995-34a63080-3fb1-11eb-9956-5d07276bb990.png) |

**Comment by jhpark-rs** [comment]
MARS는 기본적으로 3D viewer로서 엄밀하게는 2D를 지원하지 않습니다.
axial 영상에서 보시는 단면 영상도 원본 데이터 상의 정수형 index로 지정된 한 단면을 보는 것이 아니라, 
실수형 좌표로 정의되어 인접 index간 원 영상이 보간된 영상을 보여줍니다.

1 voxel 두께 지정도 가능하긴 하지만, 그럴 경우 3D view에서는 분할 영역이 거의 표시되지 않습니다.
그래서 2D 분할 경우에도 최소 3 voxel의 두께를 주고 있습니다.
2D 분할이 꼭 필요한지 생각해보시고, 추후 개발 방향을 정해야겠습니다.

**Comment by alkee-skia** [comment]
실 사용 제품에서는 위치와 크기정도만 나타내면 상품으로의 사용이 가능 하겠지만, 임상시험(계획서의 내용)에서는 ground-truth 값을 만들기 위해 병변의 모양까지 분할 되어야합니다.

최종적으로 1 voxel 두께의 분할영역이 필요한 것은 당연히 아니지만, slice 한장 한장 수정해 여러 voxel 두께의 영역을 만들거나 수정해야하는 상황에서 2D 분할이 필요한 것입니다. 3차원적인 수정이 매우 편리한 인터페이스가 있다거나, 자동으로 한번에 병변만을 분할할 수 있는 기능이 있다면, 굳이 slice 레벨(2D)의 수정이 필요하지 않을 수 있겠지만 현실적으로 어려워 보입니다.

3D view 에 나타나는 영역은 여러 slice 에 걸쳐 분할이 완료되고 나서 그 모양이 올바르게 보여지는 것이 더 중요할 것 같고, 단면(1 voxel)만을 분할하는 경우도 없겠지만 이 단면 분할을 확인하고자 3D view 를 확인하는것이 중요할 것 같지 않습니다.

2D 수정/분할 없이 이와같은 요구사항(CT 내 병변의 모양 분할)을 손쉽게 할 수 있는 방법이 있다면 제안해 주시는 것도 좋겠습니다.

**Comment by jhpark-rs** [comment]
최소단위를 1 voxel로 수정하겠습니다

**Comment by alkee-skia** [comment]
brush - eraser 의 경우 2d 로 동작하는 것을 v2008 에서 확인
