### ISSUE TITLE
livewire 사용 후 undo  동작 이상

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#59]
livewire 사용 후 undo 하는 경우 axis line 이 이상한 위치로 이동하고, 화면 이동이 되지 않는 문제가 발생

https://user-images.githubusercontent.com/49409100/103630872-a4428680-4f85-11eb-9042-1c80bcf2238d.mp4

**Comment by jhpark-rs** [comment]
undo/redo에 의한 axis line(view 위치) 변경 기능을 제거하였습니다.
참고로, axis line의 교점이 화면 바깥에 위치하게 만드는 이동(panning)은 실행 할 수 없습니다. 의도된 기능입니다.

**Comment by jhpark-rs** [comment]
v2014에서 수정 된 기능 확인하실 수 있습니다.

**Comment by Dalaway** [comment]
Undo/Redo 이후에도 위치변환 없이 Axis 유지 확인하였습니다.
