### ISSUE TITLE
CT selection 창의 overlay 불투명화

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#6]
CT selection 이 이전 상태(segmentation)를 반투명하게 overlay 하고있습니다. 불투명하게 변경해주세요.

![image](https://user-images.githubusercontent.com/49409100/93846253-78550b00-fcde-11ea-9387-ec3ac16dd902.png)

**Comment by DPseol** [comment]
개인적으로는 아래 반투명으로 보이는게 연관작업이 있어보이고, 주위에서의 반응도 좋아서 반투명 UI 작업을 한것입니다.
반투명 하는 작업 자체를 시간을 들여 작업한 결과물 임을 알아주셨으면 합니다.
반투명도는 조절할수 있습니다.

현재 일단 반투명을 제거 했습니다.

**Comment by Dalaway** [comment]
![반투명 제거](https://user-images.githubusercontent.com/67160138/96962652-3966df00-1542-11eb-8819-0d0c974566eb.PNG)
 반투명 제거 확인하였습니다
