### ISSUE TITLE
livewire 2d 사용 동작 불편함

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#60]
livewire 2d 를 사용하는 경우 모든 view tool(이동 확대 등)동작이 되지 않는데,

적어도 livewire 가 진행중인 상태가 아닌 경우(완료 또는 초기 상태 - seed 가 없는 상태?) 

slice index 이동(휠)은 가능해야 2d livewire 사용 의도에 맞을 것.

현재는 `livewire(2d) 선택 → segmentation → livewire 해제 → slice 이동 → livewire 선택 → segmentation → ...` 와 같은 단계를 거쳐야 함.

여러 slice 에 걸쳐 작업해야하는 환경이므로 이를 `livewire 선택 → segmentation → slice 이동 → segmentation → ...` 과 같이 단순화 할 필요가 있음.

**Comment by jhpark-rs** [comment]
기술하신 기능은 어차피 한장씩 분할 한다는게 실사용자를 위한 것이 아니라, 오로지 임상시 *편의*를 위한 것인데, 이를 bug라고 보는건 무리가 있습니다.
기존 계약 건과 별도로 추가 기능 개발 요청이라고 하면 구현하겠습니다.

**Comment by DPseol** [comment]
수정되었습니다. v2009 이후 버전 에서 확인 가능합니다.
livewire Action 종료후 mouse wheel 을 이용한 Slice이동, livewire Action 사용

**Comment by Dalaway** [comment]
2D Live Wire Seed 없을 시 (완료 혹은 초기상태) Mouse Wheel로 Slice Move 가능한 상황 확인하였습니다.
