### ISSUE TITLE
CT selection 중에 Segmentation 하단 바가 노출

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#7]
Segmentation 에서 CT selection 으로 되돌아 온 경우 하단에 HIDE toolbar / 환자 정보 등이 나타납니다. 이 부분도 완전히 가려져야 합니다.

![image](https://user-images.githubusercontent.com/49409100/93846392-d8e44800-fcde-11ea-8a03-00dc5f00b6a3.png)

**Comment by DPseol** [comment]
수정되었습니다.
내부 버전관리 v1937 이후 버전에서 확인 가능합니다.

**Comment by Dalaway** [comment]
![반투명 제거](https://user-images.githubusercontent.com/67160138/96962957-cd38ab00-1542-11eb-8e14-4bd09d5bbe3e.PNG)
Segmentation Bar 수정 확인되었습니다.
