### ISSUE TITLE
cancel 오타 수정

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#8]
`cancel` 버튼이 `cancle` 로 표현되고있습니다. (모든 버튼에 적용되는지 확인 필요)

![image](https://user-images.githubusercontent.com/49409100/93846494-28c30f00-fcdf-11ea-8f5a-363e7e12447a.png)

**Comment by DPseol** [comment]
언어파일 관련 수정

**Comment by alkee-skia** [comment]
[MARS1016](https://github.com/alkee-skia/mars-processor/milestone/3) 에서 수정내용 확인
