### ISSUE TITLE
한글검색이 안되는 문제

### ISSUE THREAD

**Issue by alkee-skia** [alkee-skia/mars-processor#9]
한글로 검색하는 경우 검색이 되지 않습니다. 예상하기로는 web api 를 호출할 때 [text encoding 이 UTF-8](https://en.wikipedia.org/wiki/UTF-8) 이 아니기 때문이 아닐까 의심됩니다. ( 별도의 [content-type](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Type) characterset 이 지정되지 않은경우 web server 는 UTF-8 encoding 으로 가정합니다)

![image](https://user-images.githubusercontent.com/49409100/93846816-1bf2eb00-fce0-11ea-8965-ed37d8aafff0.png)

**Comment by DPseol** [comment]
현재 영문, 숫자는 되지만 한글이 검색 안되는 경우임을 확인 했습니다.
content-type UTF-8도 해서 테스트 했는데, 경우는 같았습니다
UNICODE 형식과 연관이 있는거같은데, 추후에 시간을 조금더 들여 봐야할거같습니다.

**Comment by alkee-skia** [comment]
Method GET 과 query-string 을 사용하고있기때문에, `content-type` Request header 와는 관련이 없을 것 같습니다.

UTF-8 encoding 으로  query-string 을 보내고 있다면, [**url encoding**](https://www.w3schools.com/tags/ref_urlencode.ASP)이 올바르게 되고있는지 확인 부탁드립니다.

**Comment by DPseol** [comment]
MARS 1016 버전에서 수정 되었습니다. 확인 부탁드립니다

**Comment by alkee-skia** [comment]
[MARS1016](https://github.com/alkee-skia/mars-processor/milestone/3) 버전에서 수정 확인
